application: blogae
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

# order is important!
handlers:
- url: /static
  static_dir: static
  
- url: /admin/.*
  script: main.app
  login: admin

- url: /comment/.*
  script: main.app
  login: required

- url: /.*
  script: main.app
  login: required


